### ISSUE TITLE
Update dbsync startup params (add prune and only-utxo flags)

### ISSUE THREAD

**Issue by rdlrt** [koios-official/Lite-Node#3]

**Comment by redoracle** [comment]
when I am adding --only-utxo, I am getting invalid option. I guess in the docker version I am using that is not yet implemented.
while --prune-tx-out has been added without problems.

**Comment by rdlrt** [comment]
Need to change tag to [sancho-3-0-0](https://github.com/IntersectMBO/cardano-db-sync/pkgs/container/cardano-db-sync/160169198?tag=sancho-3-0-0)

**Comment by redoracle** [comment]
ok, change commited
